version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5  # default 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 750  # default 250
  method-complexity:
    enabled: false
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100  # default 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  pep8:
    enabled: true
  sonar-python:
    enabled: true
  # markdownlint:
  #   enabled: true
