language: python
python:
 - '3.3'
 - '3.4'
 - '3.5'
 - '3.6'
install:
 - pip install git+https://github.com/williamjameshandley/fgivenx
 - pip install .
 - pip install coveralls
script:
 - nosetests --with-coverage --cover-erase --cover-package=nestcheck
after_success:
 - coveralls
